# github Alacritty Colors

# Default colors
[colors.primary]
# background = '#070f1c'    # color for wallpaper background
background = '#040B15'
foreground = '#adbac7'

# Normal colors
[colors.normal]
black   = '#545d68'
red     = '#f47067'
green   = '#ea6847'
yellow  = '#5db2f8'
# blue    = '#2f516c'
blue    = '#3478ad'
magenta = '#b083f0'
cyan    = '#86dbf5'
white   = '#909dab'

# Bright colors
[colors.bright]
black   = '#636e7b'
red     = '#ff938a'
green   = '#6bc46d'
yellow  = '#daaa3f'
blue    = '#6cb6ff'
magenta = '#dcbdfb'
cyan    = '#56d4dd'
white   = '#cdd9e5'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ff938a'
