# github Alacritty Colors

# Default colors
[colors.primary]
# background = '#070f1c'    # color for wallpaper background
# background = '#040D19'    # color for wallpaper background
background = '#040B15'
foreground = '#adbac7'
#2c89a0
# Normal colors
[colors.normal]
black   = '#545d68'
red     = '#fd5e3a'
green   = '#73BCD9'
# green   = '#277A8C'
# green   = '#57ab5a'
# yellow  = '#1185f2'
yellow  = '#1c5280'
# yellow  = '#005580'
# blue    = '#1d6db3'
blue    = '#539bf5'
magenta = '#b083f0'
cyan    = '#39c5cf'
white   = '#909dab'

# Bright colors
[colors.bright]
black   = '#636e7b'
red     = '#ff938a'
green   = '#6bc46d'
yellow  = '#daaa3f'
blue    = '#6cb6ff'
magenta = '#dcbdfb'
cyan    = '#56d4dd'
white   = '#cdd9e5'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ff938a'
