format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_commit\
$cmd_duration\
$line_break\
$python\
$character"""

# format = "AA $fill BB $fill CC"
# right_format = """TEST"""

# [fill]
# symbol = '─'

[directory]
style = "bright-blue"

[character]
success_symbol = "[❯](bright-cyan)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$symbol$branch]($style)"
symbol = " "
style = "bright-yellow"

[git_status]
format = "[ $ahead_behind](#73BCD9)[(\\[ $all_status\\])](#204361) "
# format = "[ $all_status$ahead_behind](#73BCD9)"
# format = "[ $ahead_behind $all_status](#73BCD9)"
conflicted = "="
ahead =	"⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
up_to_date = "󰄸 "
stashed = "≡ "

# untracked = "?${count}"
# modified = "[!${count}](yellow)"
# staged = "+${count}"
# renamed = "»${count}"
# deleted = "[-${count}](red)"

# outline file icon
untracked ="[󱀶 ${count} ](#3c6f99)"
modified = "[󱋢 ${count} ](#719ead)"
staged = "[󰻭 ${count} ](#55ab89)"
# staged = "[󰻭 ${count} ](#86afbd)"
renamed = "[󰬳 ${count} ](#539bf5)"
deleted = "[󱪢 ${count} ](#c25951)"


[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

# [git_state]
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
symbol = " "
format = "[$virtualenv]($style) "
style = "bright-yellow"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

# # SYMBOLS

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[haskell]
symbol = "λ "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true
